# -*- coding: utf-8 -*-
"""Copy of Plotly Bar chart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UzQXjFpp2_ut4Nx3__g_wB_pe_40aH8n

# Contents

1. Importing libraries
2. Declaring the dataframe
3. Basic Bar Chart
4. Adjusting the chart size
5. Adjusting bar Width
6. Adding data labels
7. Customizing data labels
8. Adding chart title
9. Changing Bar colour
10. Changing chart theme

### 1. Importing Libraries
"""

import plotly #Used for plotting
import pandas as pd #Used to handle dataframes
import plotly.express as px

"""###2. Declaring Dataframe"""

# Create the pandas DataFrame
df = pd.DataFrame([['Nick', 10], ['Tom', 15], ['Ram', 14]], columns = ['Name', 'Age'])
# print dataframe.
df

"""###3. Basic Bar Chart"""

fig = px.bar(df, x='Name', y='Age')
fig.show()

"""###4. Adjusting chart size"""

fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600)
fig.show()

"""###. 5. Adjusting Bar Width"""

#we want reduces width
fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600)
fig.update_traces(width=0.2) #Bar width
fig.show()

"""###6. Add Data Labels"""

#text_auto=True
fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600, text_auto=True)
fig.update_traces(width=0.5) #Bar width
fig.show()

"""###7. Customizing data labels"""

#text_fontsize =26 is the text_auto values increase or decreases based on textfont_size
#textangle is the  slight down or left like 0,1,....etc
fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600, text_auto=True)
#fig.update_traces(width=0.5, textposition="outside")
fig.update_traces(width=0.5,textfont_size=12, textangle=10, textposition="outside")
#fig.update_traces(width=0.5,textfont_size=12, textangle=0, textposition="outside")

fig.show()

"""### 8. Adding Chart Title"""

#title will be left or center or right printed based on values
#title_x=0 to 1 range only
fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600, text_auto=True)
fig.update_traces(width=0.5,textfont_size=12, textangle=0, textposition="outside")
fig.update_layout(title_text='Age Across Names', title_x=1
                  )
fig.show()

"""### 9. Changing Bar colour"""

fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600, text_auto=True)
fig.update_traces(width=0.5,textfont_size=12, textangle=0, textposition="outside",marker_color='turquoise')
fig.update_layout(title_text='Age Across Names', title_x=0.5)
fig.show()

"""### 10. Changing Theme of the chart"""

#ctempleate element few of template that will be iterate over here 0,1,2,3,4......
for template_element in ["plotly", "plotly_white", "plotly_dark", "ggplot2", "seaborn", "simple_white", "none"]:
    fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600, text_auto=True, template=template_element)
    fig.update_traces(width=0.5,textfont_size=12, textangle=0, textposition='outside')
    fig.update_layout(title_text='Age Across Names', title_x=0.5)

    fig.update_traces(marker_color='turquoise')
    fig.show()

#here taking single color
fig = px.bar(df, x='Name', y='Age',
                 width=1000, height=600, text_auto=True, template="plotly_white")
fig.update_traces(width=0.5,textfont_size=12, textangle=0, textposition="outside")
fig.update_layout(title_text='Age Across Names', title_x=0.5)
fig.update_traces(marker_color='turquoise')
fig.show()

# Create the pandas DataFrame
df = pd.DataFrame([['Doctor', 30000], ['Consultant', 25000], ['Construction Worker', 15000],
                  ['Software Engineer', 28000],['Chef', 25000] ], columns = ['Occupation', 'Average Salary'])
# print dataframe.
df

fig = px.bar(df, x='Occupation', y='Average Salary',
                 width=1000, height=600, text_auto=True, template="plotly_white")
fig.update_traces(width=0.5,textfont_size=12, textangle=0, textposition="outside")
fig.update_layout(title_text='Average Salary Across Occupation', title_x=0.5)
fig.update_traces(marker_color='turquoise')
fig.show()

