# -*- coding: utf-8 -*-
"""Plotly Line Chart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ch_lYrg9ATHAvYQfa37tf0-g4f5E0v0H

# Contents

1. Importing libraries
2. Declaring the dataframe
3. Basic Line Chart
4. Adjusting the chart size
5. Adding line-markers
6. Adding data labels
7. Customizing data labels
8. Adding chart title
9. Changing Bar colour
10. Changing chart theme

### 1. Importing Libraries
"""

import plotly #Used for plotting
import pandas as pd #Used to handle dataframes
import plotly.express as px

"""###2. Declaring Dataframe"""

# Create the pandas DataFrame
df = pd.DataFrame([[20, 10], [30, 15], [40, 14],[50, 18],[60, 20]], columns = ['Weight', 'Height'])
# print dataframe.
df

"""###3. Basic line Chart"""

fig = px.line(df, x='Weight', y='Height')
fig.show()

"""###4. Adjusting chart size"""

fig = px.line(df,  x='Weight', y='Height',
                 width=1000, height=600)
fig.show()

"""###. 5. Adding markers"""

fig = px.line(df,  x='Weight', y='Height',
                 width=1000, height=600,markers=True)
fig.update_traces(marker_size=10)
fig.show()

"""###6. Add Data Labels"""

fig = px.line(df,  x='Weight', y='Height',
                 width=1000, height=600,markers=True,text='Height')
fig.update_traces(marker_size=10)
fig.show()

"""###7. Customizing data labels"""

fig = px.line(df,  x='Weight', y='Height',
                 width=1000, height=600,markers=True,text='Height')
fig.update_traces(textposition="top center")
fig.update_traces(marker_size=10)
fig.show()

"""### 8. Adding Chart Title"""

fig = px.line(df,  x='Weight', y='Height',
                 width=1000, height=600,markers=True,text='Height')
fig.update_traces(textposition="top center",marker_size=10)
fig.update_layout(title_text='Height Across Weights', title_x=0.5)
fig.show()

"""### 9. Changing Line colour"""

fig = px.line(df,  x='Weight', y='Height',
                 width=1000, height=600,markers=True,text='Height')
fig.update_traces(textposition="top center",line_color='turquoise',marker_size=10)
fig.update_layout(title_text='Height Across Weights', title_x=0.5)
fig.show()

"""### 10. Changing Theme of the chart"""

for template_element in ["plotly", "plotly_white", "plotly_dark", "ggplot2", "seaborn", "simple_white", "none"]:
    fig = px.line(df,  x='Weight', y='Height',
                 width=1000, height=600,markers=True,text='Height',template=template_element)
    fig.update_traces(textposition="top center",line_color='turquoise',marker_size=10)
    fig.update_layout(title_text='Height Across Weights', title_x=0.5)
    fig.show()



